deliver sourcemaps for modules
Signed-off-by: vwfox <markus.hochstein@software-hochstein.de>

diff --git a/.github/workflows/ts_yarn_build.yml b/.github/workflows/ts_yarn_build.yml
--- a/.github/workflows/ts_yarn_build.yml
+++ b/.github/workflows/ts_yarn_build.yml
@@ -24,15 +24,16 @@ jobs:
           node-version: 20.x
       - name: Build
         working-directory: ./packages/app/default
-        run: yarn --skip-integrity-check --no-lockfile --network-timeout 100000
+        #run: yarn --skip-integrity-check --no-lockfile --network-timeout 100000
+        run: yarn --immutable --network-timeout 100000
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9
-      - name: Check for uncommitted changes in yarn.lock
-        run: |
-          if git diff --name-only | grep -q "^yarn.lock"; then
-            echo "::error::The yarn.lock file has uncommitted changes!"
-            exit 1
-          fi
+      #- name: Check for uncommitted changes in yarn.lock
+      #  run: |
+      #    if git diff --name-only | grep -q "^yarn.lock"; then
+      #      echo "::error::The yarn.lock file has uncommitted changes!"
+      #      exit 1
+      #    fi
       #- name: Create eslint json report
       #  run: |
       #    yarn lint:ci
